'use strict';
const $=id=>document.getElementById(id),{presets,calculate,phaseNoise,db,C}=RadarModel;
let p={...presets['generic']},m=calculate(p),view='system',selected='';
const colors={tx:'#56deb7',rx:'#60b8fa',clk:'#ecb75d',dig:'#b8a0ff',muted:'#9baec4',grid:'#29394d',danger:'#ff8589'};
const groups=[['目标与场景 · 假设',true,[['r','目标距离',.5,100,.1,'m'],['v','径向速度',-10,10,.1,'m/s'],['rcs','目标 RCS',-40,20,1,'dBsm'],['alpha','大气比衰减',0,30,.5,'dB/km']]],['波形与采样 · 假设',true,[['fc','扫频中心',24,300,1,'GHz'],['bw','扫频带宽',.1,24,.1,'GHz'],['tc','扫频时间',50,500,5,'μs'],['idle','空闲时间',0,100,5,'μs'],['n','相干 Chirp 数',1,256,1,''],['fs','外部 ADC 采样率',2,100,1,'MS/s']]],['功率与接收 · 假设',false,[['eirp','定向 EIRP',0,35,.1,'dBm'],['einf','等效 EINF',0,25,.1,'dB'],['loss','额外链路损耗',0,20,.5,'dB'],['ifbw','IF 低通截止',.5,15,.5,'MHz']]],['外部 ADC · 假设',false,[['enob','ADC 有效位数',6,14,.5,'bit'],['backoff','输入满量程回退',0,60,1,'dB'],['jitter','ADC 总抖动',.05,10,.05,'ps']]],['相噪与检测 · 假设',false,[['pn','PLL @100 kHz',-120,-70,1,'dBc/Hz'],['threshold','所需检测 SNR',3,25,.5,'dB'],['impl','窗与实现损耗',0,10,.5,'dB']]]];
const spec=Object.fromEntries(groups.flatMap(g=>g[2]).map(x=>[x[0],x]));
$('parameters').innerHTML=groups.map(([name,open,fields])=>`<details ${open?'open':''}><summary>${name}</summary>${fields.map(([key,label,min,max,step,unit])=>`<div class="param"><div class="param-top"><label for="s-${key}">${label}</label><div class="param-value"><input id="n-${key}" data-key="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${p[key]}" aria-label="${label}数值"><span class="unit">${unit}</span></div></div><input type="range" id="s-${key}" data-key="${key}" aria-label="${label}" min="${min}" max="${max}" step="${step}" value="${p[key]}"></div>`).join('')}</details>`).join('');
const filterControl=$('s-ifbw');const filterSelect=document.createElement('select');filterSelect.id='s-ifbw';filterSelect.dataset.key='ifbw';filterSelect.setAttribute('aria-label','IF 低通截止');filterSelect.innerHTML=[.5,1,3,10,15].map(v=>`<option value="${v}">${v} MHz</option>`).join('');filterSelect.value=p.ifbw;filterControl.replaceWith(filterSelect);$('n-ifbw').readOnly=true;
function fill(k){const r=$('s-'+k),s=spec[k];r.style.setProperty('--p',((p[k]-s[2])/(s[3]-s[2])*100).toFixed(2)+'%');}
function sync(){Object.keys(spec).forEach(k=>{$('s-'+k).value=p[k];$('n-'+k).value=p[k]});}
let raf=0;function schedule(){cancelAnimationFrame(raf);raf=requestAnimationFrame(render);}
$('parameters').addEventListener('input',e=>{const k=e.target.dataset.key;if(!k)return;const v=Number(e.target.value);if(!Number.isFinite(v))return;const s=spec[k];if(v<s[2]||v>s[3])return;p[k]=v;$('s-'+k).value=v;if(e.target.type==='range')$('n-'+k).value=v;schedule();});
$('parameters').addEventListener('change',e=>{const k=e.target.dataset.key;if(!k)return;const s=spec[k];const v=Number(e.target.value);p[k]=Number.isFinite(v)?Math.max(s[2],Math.min(s[3],Math.round(v/s[4])*s[4])):p[k];sync();render();});
$('preset').addEventListener('change',()=>{p={...presets[$('preset').value]};sync();render();});
$('reset').addEventListener('click',()=>{p={...presets[$('preset').value]};sync();render();});
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce){document.body.classList.add('paused');$('motion').setAttribute('aria-pressed','false');$('motion').textContent='▶ 播放信号流';}
$('motion').addEventListener('click',()=>{const paused=document.body.classList.toggle('paused');$('motion').setAttribute('aria-pressed',String(!paused));$('motion').textContent=paused?'▶ 播放信号流':'Ⅱ 暂停信号流';});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==view);document.querySelectorAll('[data-view]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));render();}));
const fmt=(x,n=1)=>Number.isFinite(x)?x.toFixed(n):'—',sgn=x=>(x>=0?'+':'')+fmt(x),ghz=x=>String(+x.toFixed(2));
const {modules,relationships}=window.PaperData;let channelSelected=null;const repeatedModules=new Set(['vga','vmps','mult','pa','txant','rxant','lna','doubler','mixer','if']);const txModules=new Set(['vga','vmps','mult','pa','txant']);
function schematic(){
 if(window.RadarScene)window.RadarScene.update(p,m,selected,channelSelected);
 if(!selected){$('moduleDetail').classList.add('idle');$('moduleDetail').textContent='点击一颗芯片或天线，展开它的名称、职责和上下游连接。';$('moduleConnections').innerHTML='';document.querySelectorAll('#modulePicker [data-module]').forEach(b=>b.setAttribute('aria-pressed','false'));return;}
 $('moduleDetail').classList.remove('idle');
 const detail=modules[selected];
 const met=selected==='pa'||selected==='txant'?`当前定向 EIRP ${fmt(p.eirp)} dBm · 包含 TX 增益与馈线损耗`:selected==='target'?`距离 ${fmt(p.r)} m · RCS ${fmt(p.rcs)} dBsm · τ ${fmt(m.tau*1e9)} ns`:selected==='mixer'?`RF ${fmt(p.fc)} GHz · LO ${fmt(p.fc/2)} GHz → 差分 IF |fb| ${fmt(Math.abs(m.beat)/1e6,3)} MHz`:selected==='adc'||selected==='sample'?`每个 RX 的 fs ${fmt(p.fs)} MS/s · ${p.enob} ENOB · ${p.jitter} ps RMS 抖动`:selected==='pll'?`PLL 中心 ${fmt(p.fc/p.mult,2)} GHz · 扫频斜率 ${fmt(m.slope/1e12,1)} MHz/μs（RF 端）`:selected==='mult'?`${fmt(p.fc/p.mult,2)} GHz × ${p.mult} → ${fmt(p.fc,2)} GHz`:selected==='splitter'?`${fmt(p.fc/4,2)} GHz · DA → 1:8 → 4 TX + 4 RX LO`:selected==='doubler'?`${fmt(p.fc/4,2)} → ${fmt(p.fc/2,2)} GHz · SHM 使用二次谐波`:selected==='vga'?`${fmt(p.fc/4,2)} GHz · 调节发射支路幅度`:selected==='vmps'?`${fmt(p.fc/4,2)} GHz 端 90° 相移，经 ×4 映射为 RF 端 360°`:selected==='if'?`IF 单边通带 ${p.ifbw} MHz · |fb| ${fmt(Math.abs(m.beat)/1e6,3)} MHz`:selected==='lna'||selected==='rxant'?`接收等效 EINF ${fmt(p.einf)} dB · 预算未重复叠加天线增益`:selected==='dsp'?`${p.n} chirps · 帧长 ${fmt(p.n*m.Tr*1000,2)} ms · 理想热噪声 SNR ${fmt(m.snr)} dB`:'';
 $('moduleDetail').innerHTML=`<div class="selected-heading"><strong>${channelSelected?(txModules.has(selected)?'TX':'RX')+channelSelected+' · ':''}${detail[0]}</strong><div class="detail-actions"><button id="focusSelected">飞近观察 ↗</button><button id="clearSelected" aria-label="收起模块详情">收起 ×</button></div></div>${repeatedModules.has(selected)?`<div class="channel-picker"><span>选择通道</span>${[1,2,3,4].map(n=>`<button data-channel="${n}" aria-pressed="${n===channelSelected}">${txModules.has(selected)?'TX':'RX'}${n}</button>`).join('')}</div>`:''}<p>${detail[1]}</p><span class="paper-status">${detail[2]}</span>${met?`<div class="entity-readout">${met}</div>`:''}`;
 $('moduleDetail').querySelectorAll('[data-channel]').forEach(b=>b.addEventListener('click',()=>chooseModule(selected,Number(b.dataset.channel))));
 $('clearSelected').addEventListener('click',()=>chooseModule(''));
 $('moduleConnections').innerHTML=selected?`<span>关联模块</span>${relationships[selected].map(k=>`<button data-module="${k}">${modules[k][0].split(' / ')[0]} ↗</button>`).join('')}`:'';
 $('moduleConnections').querySelectorAll('[data-module]').forEach(b=>b.addEventListener('click',()=>chooseModule(b.dataset.module,channelSelected)));
 const f=$('focusSelected');if(f)f.addEventListener('click',()=>window.RadarScene?.focus(selected));
 document.querySelectorAll('#modulePicker [data-module]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.module===selected)));
}
function chooseModule(id,channel=null){if(id&&!modules[id])return;selected=id;channelSelected=repeatedModules.has(id)?(channel||1):null;schematic();}
$('modulePicker').innerHTML=Object.keys(modules).map(k=>`<button data-module="${k}" aria-pressed="false">${({package:'系统载板',ref:'参考时钟',pll:'扫频 PLL',vga:'TX VGA',vmps:'TX VMPS',mult:'TX ×4',splitter:'35G DA / 分配',doubler:'RX ×2',pa:'TX 功放',txant:'TX 天线',rxant:'RX 天线',lna:'LNA',mixer:'SHM',if:'模拟 IF',adc:'外部 ADC',dsp:'DSP',sample:'采样时钟',power:'电源 / 控制',target:'目标'})[k]||k.toUpperCase()}</button>`).join('');
$('modulePicker').querySelectorAll('[data-module]').forEach(b=>b.addEventListener('click',()=>chooseModule(b.dataset.module,channelSelected)));
window.addEventListener('radar-scene-select',e=>chooseModule(e.detail.id,e.detail.channel));
window.addEventListener('radar-scene-ready',()=>{schematic();});

function chart(id,{xlim,ylim,xLabel,yLabel,series=[],hLines=[],vLines=[],annotation='',heat=null,xLog=false}){
 const el=$(id);if(!el||el.closest('[hidden]'))return;const w=Math.max(200,el.clientWidth-10),h=el.clientHeight-4,L=w<300?48:58,R=17,T=annotation?45:29,D=42,pw=w-L-R,ph=h-T-D;const xx=v=>L+(xLog?(Math.log10(v)-Math.log10(xlim[0]))/(Math.log10(xlim[1])-Math.log10(xlim[0])):(v-xlim[0])/(xlim[1]-xlim[0]))*pw, yy=v=>T+(ylim[1]-v)/(ylim[1]-ylim[0])*ph;
 const niceTicks=(lo,hi,n)=>{const raw=(hi-lo)/n,m=10**Math.floor(Math.log10(raw)),f=raw/m,st=(f<1.5?1:f<3?2:f<7?5:10)*m,out=[];for(let v=Math.ceil(lo/st-1e-9)*st;v<=hi+st*1e-9;v+=st)out.push(Math.abs(v)<st*1e-6?0:+v.toPrecision(12));return out;};
 const tickLabel=v=>{const a=Math.abs(v),t=x=>String(+x.toPrecision(3));return a>=1e6?t(v/1e6)+'M':a>=1e3?t(v/1e3)+'k':t(v);};
 const decades=[];for(let d=Math.ceil(Math.log10(xlim[0])-1e-9);xLog&&d<=Math.floor(Math.log10(xlim[1])+1e-9);d++)decades.push(10**d);
 const xTicks=xLog&&decades.length>=2?decades:niceTicks(xlim[0],xlim[1],w<330?3:5),yTicks=niceTicks(ylim[0],ylim[1],4);
 let z=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${xLabel}与${yLabel}曲线"><defs><clipPath id="clip-${id}"><rect x="${L}" y="${T}" width="${pw}" height="${ph}"/></clipPath></defs>`;
 for(const v of xTicks){const x=xx(v),anchor=x>L+pw-14?'end':x<L+14?'start':'middle';z+=`<line x1="${x}" y1="${T}" x2="${x}" y2="${T+ph}" stroke="${colors.grid}" stroke-width=".6"/><text x="${x}" y="${T+ph+17}" text-anchor="${anchor}" fill="${colors.muted}" font-size="11.5">${tickLabel(v)}</text>`;}
 for(const v of yTicks){const y=yy(v);z+=`<line x1="${L}" y1="${y}" x2="${L+pw}" y2="${y}" stroke="${colors.grid}" stroke-width=".6"/><text x="${L-7}" y="${y+4}" text-anchor="end" fill="${colors.muted}" font-size="11.5">${tickLabel(v)}</text>`;}
 z+=`<text x="${L}" y="14" fill="${colors.muted}" font-size="12">${yLabel}</text><text x="${L+pw}" y="${h-3}" text-anchor="end" fill="${colors.muted}" font-size="12">${xLabel}</text><g clip-path="url(#clip-${id})">`;
 if(heat){const nx=56,ny=35;for(let i=0;i<nx;i++)for(let j=0;j<ny;j++){const rv=xlim[0]+(i+.5)/nx*(xlim[1]-xlim[0]),vv=ylim[0]+(j+.5)/ny*(ylim[1]-ylim[0]),delta=((rv-heat.r)/heat.rs)**2+((vv-heat.v)/heat.vs)**2;const val=Math.exp(-delta*.5);z+=`<rect x="${L+i*pw/nx}" y="${T+(ny-j-1)*ph/ny}" width="${pw/nx+.2}" height="${ph/ny+.2}" fill="${val>.4?colors.tx:colors.rx}" opacity="${.045+.92*val}"/>`;}z+=`<circle cx="${xx(heat.r)}" cy="${yy(heat.v)}" r="4" fill="none" stroke="#e6fff7" stroke-width="1"/>`;}
 for(const l of hLines)z+=`<line x1="${L}" y1="${yy(l.value)}" x2="${L+pw}" y2="${yy(l.value)}" stroke="${l.color||colors.clk}" stroke-dasharray="4 4" stroke-width="1"/>`;
 for(const l of vLines)z+=`<line x1="${xx(l.value)}" y1="${T}" x2="${xx(l.value)}" y2="${T+ph}" stroke="${l.color||colors.clk}" stroke-dasharray="4 4" stroke-width="1"/>`;
 for(const line of series){let path='',pen=false;for(const a of line.data){if(!Number.isFinite(a[0])||!Number.isFinite(a[1])){pen=false;continue;}path+=(pen?'L':'M')+xx(a[0]).toFixed(2)+','+yy(a[1]).toFixed(2);pen=true;}z+=`<path d="${path}" fill="none" stroke-linejoin="round" stroke-linecap="round" stroke="${line.color}" stroke-width="${line.width||1.8}" ${line.dash?'stroke-dasharray="4 4"':''}/>`;}z+='</g>';
 if(annotation)z+=`<text x="${L}" y="32" fill="#d4e4f1" font-size="12" text-anchor="start">${annotation}</text>`;
 z+=`<rect x="${L}" y="${T}" width="${pw}" height="${ph}" fill="transparent" stroke="#33475f"><title>${series.map(q=>q.label||'').filter(Boolean).join(' / ')}</title></rect></svg>`;el.innerHTML=z;
}
const samples=(a,b,n,fn)=>Array.from({length:n},(_,i)=>{let x=a+(b-a)*i/(n-1);return [x,fn(x)];});
function chirp(id){const end=2*(p.tc+p.idle),a=[],b=[];for(let i=0;i<440;i++){const t=i/439*end,local=t%(p.tc+p.idle);a.push([t,local<=p.tc?local/p.tc*p.bw:NaN]);const rt=t-m.tau*1e6,rLocal=((rt%(p.tc+p.idle))+(p.tc+p.idle))%(p.tc+p.idle);b.push([t,rt>=0&&rLocal<=p.tc?rLocal/p.tc*p.bw+m.fd/1e9:NaN]);}chart(id,{xlim:[0,end],ylim:[0,p.bw*1.08],xLabel:'时间 (μs)',yLabel:'Δf (GHz)',series:[{data:a,color:colors.tx,label:'TX'},{data:b,color:colors.rx,label:'RX',dash:true}],annotation:'TX ━  RX ┄ · τ = '+fmt(m.tau*1e6,m.tau<1e-6?3:2)+' μs'+(m.tau*1e6<.01*(p.tc+p.idle)?(id==='miniChirp'?' · 重合':'（按比例，与 TX 重合）'):'')});}
function range(id){const half=Math.max(6*m.effectiveRes,.02),center=m.apparentR;const sinc=x=>Math.abs(x)<1e-8?1:Math.sin(Math.PI*x)/(Math.PI*x);chart(id,{xlim:[center-half,center+half],ylim:[-60,3],xLabel:'表观距离 (m)',yLabel:'幅度 (dB)',series:[{data:samples(center-half,center+half,440,r=>Math.max(-60,20*Math.log10(Math.abs(sinc((r-center)/m.effectiveRes))))),color:colors.rx}],vLines:[{value:p.r,color:colors.tx}],annotation:'峰值位置 '+fmt(center,2)+' m · 绿虚线 = 真实 R'});}
function rd(id){const half=7*m.effectiveRes;chart(id,{xlim:[m.apparentR-half,m.apparentR+half],ylim:[-m.vmax,m.vmax],xLabel:'表观距离 (m)',yLabel:'速度 (m/s)',heat:{r:m.apparentR,v:m.vAlias,rs:m.effectiveRes*.5,vs:Math.max(m.vres*.55,2*m.vmax/35)},annotation:Math.abs(p.v)>=m.vmax?'速度已折返':'归一化主瓣'});}
function results(){const metric=(label,val,unit,note,extra='')=>`<div class="metric ${extra}"><div class="metric-label">${label}</div><div class="metric-value">${val}<span>${unit}</span></div><div class="metric-note">${note}</div></div>`;
 $('primaryMetrics').innerHTML=metric('教学相干 SNR',fmt(m.snr),'dB','当前假设 · 热噪声能量预算','primary '+(m.margin<0?'warn':''))+metric('检测裕量',sgn(m.margin),'dB','设计门限 '+fmt(p.threshold)+' dB',m.margin<0?'warn':'')+metric('各向同性等效回波',fmt(m.pr),'dBm','EIRP / EINF 口径；非 LNA 端口功率')+metric('有效距离分辨尺度',fmt(m.effectiveRes*100,2),'cm','名义 c/2B = '+fmt(m.rangeRes*100,2)+' cm')+metric('无模糊速度', '±'+fmt(m.vmax),'m/s','速度分辨率 '+fmt(m.vres,3)+' m/s')+metric('限距：热噪声 / IF',fmt(m.thermalRange,0)+' / '+fmt(m.rangeIF,0),'m','当前假设 · IF 含 |fD| 留量');
 $('constraints').innerHTML=m.checks.map(q=>`<div class="check ${q.ok?'ok':'fail'}"><b>${q.ok?'✓':'!'}</b><div>${q.name}<small>${q.detail}</small></div></div>`).join('');
}
function budget(){
 $('budgetEquation').textContent='Pr,iso = EIRP + RCS + 20log₁₀λ − 30log₁₀(4π) − 40log₁₀R − Lextra − 2αR/1000';
 // Waterfall: each term moves the running level; totals are drawn from the section baseline.
 const powerSteps=[['定向 EIRP（可调）',p.eirp,'dBm','level'],['目标 RCS（假设）',p.rcs,'dBsm','delta'],['波长 / 球面扩散项',m.spread,'dB','delta'],['附加链路损耗（假设）',-p.loss,'dB','delta'],['双程大气损耗（假设）',-m.atm,'dB','delta'],['各向同性等效回波 Pr,iso',m.pr,'dBm','total'],['热噪声 kT₀Bn + EINF',m.noise,'dBm','noise']];
 const snrSteps=[['输入 SNR = Pr,iso − 噪声',m.snrIn,'dB','level'],['处理增益 10log₁₀(Bn·Tobs·N)',m.processing,'dB','delta'],['窗与实现损耗（假设）',-p.impl,'dB','delta'],['教学相干 SNR',m.snr,'dB','total']];
 const section=(title,unit,steps,base,marks)=>{let level=0;const spans=steps.map(([,v,,kind])=>{if(kind==='delta'){const a=level;level+=v;return [a,level];}if(kind!=='noise')level=v;return [base,v];});const all=spans.flat().filter(Number.isFinite).concat(marks.map(x=>x.value)),lo=Math.floor((Math.min(...all)-6)/10)*10,hi=Math.ceil((Math.max(...all)+6)/10)*10,pct=v=>((v-lo)/(hi-lo)*100).toFixed(2);
  const ticks=marks.map(x=>`<i class="budget-mark ${x.cls}" style="left:${pct(x.value)}%" title="${x.label}"></i>`).join('');
  return `<div class="budget-section"><span>${title}</span><small>${lo} … ${hi} ${unit}${marks.length?' · '+marks.map(x=>x.label).join(' · '):''}</small></div>`+steps.map(([name,v,u,kind],i)=>{const [a,b]=spans[i].map(x=>x??lo),left=Math.min(a,b),cls=kind==='delta'?(v>=0?'gain':'negative'):kind;return `<div class="budget-row ${kind==='total'?'total':''}"><span>${name}</span><div class="bar-track">${ticks}<div class="bar ${cls}" style="left:${pct(left)}%;width:max(2px,${(Math.abs(b-a)/(hi-lo)*100).toFixed(2)}%)"></div></div><strong>${kind==='delta'&&v>=0?'+':''}${fmt(v)} ${u}</strong></div>`;}).join('');};
 $('budgetRows').innerHTML=section('功率电平','dBm',powerSteps,null,[])+section('信噪比','dB',snrSteps,0,[{value:0,cls:'zero',label:'竖线 0 dB'},{value:p.threshold,cls:'threshold',label:'黄线 检测门限 '+fmt(p.threshold)+' dB'}]);
 const maxR=Math.min(500,Math.max(p.r*1.5,m.thermalRange*1.2,m.rangeIF*1.2,5)),minR=.5;chart('snrChart',{xlim:[minR,maxR],ylim:[Math.min(-20,m.snr-10),Math.max(60,m.snr+10)],xLabel:'距离 (m)',yLabel:'教学 SNR (dB)',series:[{data:samples(minR,maxR,300,m.snrAt),color:colors.tx}],hLines:[{value:p.threshold}],vLines:[{value:p.r,color:colors.rx},{value:m.rangeIF,color:colors.danger}],annotation:'黄：门限 · 蓝：当前 R · 红：IF 限距'});
 const maxIfR=Math.max(p.r*1.3,m.rangeIF*1.3,5);chart('dynamicChart',{xlim:[0,maxIfR],ylim:[0,Math.max(p.fs/2,p.ifbw,Math.abs(m.beat)/1e6)*1.3],xLabel:'距离 (m)',yLabel:'频率 (MHz)',series:[{data:samples(0,maxIfR,200,r=>Math.abs(m.slope*2*r/C-m.fd)/1e6),color:colors.rx}],hLines:[{value:p.ifbw,color:colors.tx},{value:p.fs/2,color:colors.clk}],vLines:[{value:p.r,color:colors.muted}],annotation:'蓝：|fb| · 绿：LPF · 黄：fs/2 · 灰：当前 R'});
 $('dynamicText').textContent=`当前 |fb| = ${fmt(Math.abs(m.beat)/1e6,3)} MHz；LPF ${p.ifbw} MHz；假设外部 ADC 为 ${p.fs} MS/s。IF 通带与抗混叠条件需要同时满足；这里未模拟实际滤波器滚降。`;
 $('budgetExplanation').innerHTML=`<p><b>参考面：</b>EIRP = Pt + G_TX − L_TX；EINF = NF_RX − G_RX（dB，接收馈线损耗应计入等效 NF_RX）。因此预算不再额外叠加 TX / RX 天线增益，也不增加虚拟的多通道合并增益。</p><p>LPF 截止 ${fmt(p.ifbw)} MHz 作为差分实数 IF 的等效矩形噪声带宽近似，Bn = ${fmt(m.noiseBW/1e6)} MHz。有效 Tobs = Tc − τ = ${fmt(m.Tobs*1e6,3)} μs。输入噪声 ${fmt(m.noise)} dBm，输入 SNR ${fmt(m.snrIn)} dB。</p><p>处理增益 10log₁₀(Bn·Tobs·N) = ${fmt(m.processing)} dB。相干 SNR = ${fmt(m.snrIn)} + ${fmt(m.processing)} − ${fmt(p.impl)} = ${fmt(m.snr)} dB，等价于 Pr,iso·N·Tobs / (kT₀·Fiso) 再扣实现损耗。四路接收分别得到差分 IF；本预算不额外增加四路合并增益，也不把 4TX×4RX 直接当成 16 个虚拟通道。</p><p>当前热噪声限距 ${fmt(m.thermalRange)} m、IF 限距 ${fmt(m.rangeIF)} m 仅适用于左侧假设。几何外形不限制计算频段，但实际电路需按带宽、增益、功率和线性度重新设计；本页不验证器件可实现性。</p>`;

}
function wave(){chirp('chirpChart');const f=Math.abs(m.beat),dur=Math.min(m.Tobs*1e6,6/Math.max(f,1)*1e6);chart('beatChart',{xlim:[0,Math.max(.001,dur)],ylim:[-1.15,1.15],xLabel:'局部时间 (μs)',yLabel:'归一化幅度',series:[{data:samples(0,Math.max(.001,dur),400,t=>Math.cos(2*Math.PI*m.beat*t*1e-6)),color:colors.rx}],annotation:'f_b = '+fmt(m.beat/1e6,3)+' MHz'});range('rangeChart');rd('rdChart');const values=[['扫频斜率',fmt(m.slope/1e12,2)+' MHz/μs','S = B / Tramp'],['传播往返延迟',fmt(m.tau*1e9,2)+' ns','τ = 2R/c'],['Doppler 频移',fmt(m.fd/1000,2)+' kHz','fD = 2v/λ'],['有效样点数',m.ns,'floor(fs · Tobs)'],['帧观测时长',fmt(p.n*m.Tr*1000,2)+' ms','N · Trep'],['速度折返结果',fmt(m.vAlias,2)+' m/s','限于 ±vmax']];$('waveNumbers').innerHTML=values.map(([a,b,c])=>`<div class="number-cell"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('');}
function clock(){const freqs=Array.from({length:280},(_,i)=>10**(3+4*i/279));const pn=freqs.map(f=>phaseNoise(p,m,f));chart('pnChart',{xlim:[1e3,1e7],ylim:[-160,Math.max(-30,p.pn+40+20*Math.log10(p.mult))],xLog:true,xLabel:'谱线偏移 (Hz)',yLabel:'相噪 (dBc/Hz)',series:[{data:freqs.map((f,i)=>[f,pn[i].src]),color:colors.muted,dash:true},{data:freqs.map((f,i)=>[f,pn[i].rf]),color:colors.clk},{data:freqs.map((f,i)=>[f,pn[i].IF]),color:colors.rx}],annotation:'灰：PLL / 黄：RF / 蓝：IF'});const jitterData=samples(.05,10,200,j=>-20*Math.log10(Math.max(1e-18,2*Math.PI*Math.abs(m.beat)*j*1e-12)));chart('jitterChart',{xlim:[.05,10],ylim:[Math.min(20,m.snrQsignal-5),Math.max(m.snrQ,jitterData[0][1])+8],xLabel:'总 RMS 抖动 (ps)',yLabel:'单项 SNR 上限 (dB)',series:[{data:jitterData,color:colors.clk}],hLines:[{value:m.snrQ,color:colors.rx},{value:m.snrQsignal,color:colors.danger}],vLines:[{value:p.jitter,color:colors.muted}],annotation:'黄：抖动上限 · 蓝：满量程 · 红：输入量化 · 灰：当前抖动'});$('multLabel').textContent=ghz(p.fc/4)+' GHz · DA / 1:8';$('clockNumbers').innerHTML=[['当前抖动上限',fmt(m.snrJ)+' dB'],['满量程 ENOB 上限',fmt(m.snrQ)+' dB'],['假设输入回退',fmt(m.backoff)+' dB'],['假设输入量化 SNR',fmt(m.snrQsignal)+' dB']].map(([a,b])=>`<div class="number-cell"><span>${a}</span><strong>${b}</strong></div>`).join('');}
function render(){Object.keys(spec).forEach(fill);m=calculate(p);$('fcHeading').textContent=fmt(p.fc,0);$('legendRF').textContent=ghz(p.fc);$('legendHalf').textContent=ghz(p.fc/2);$('legendQuarter').textContent=ghz(p.fc/4);results();if(view==='system'){schematic();chirp('miniChirp');range('miniRange');rd('miniRD');}else if(view==='budget')budget();else if(view==='wave')wave();else if(view==='clock')clock();}
document.querySelectorAll('[data-experiment]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.experiment;if(action==='distance')p.r=Math.min(100,p.r*2);if(action==='bandwidth')p.bw=Math.min(24,p.bw+4);if(action==='chirps')p.n=Math.min(256,p.n*2);sync();view='budget';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==view);document.querySelectorAll('[data-view]').forEach(t=>t.setAttribute('aria-pressed',String(t.dataset.view===view)));render();}));
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(render,100);});
// Optional agent interface shares exactly the same local parameter state as the controls.
if(document.modelContext?.registerTool){const life=new AbortController();const props=Object.fromEntries(Object.entries(spec).map(([k,s])=>[k,{type:'number',minimum:s[2],maximum:s[3],description:s[1]+' ('+s[5]+')'}]));try{Promise.resolve(document.modelContext.registerTool({name:'configure_radar_parameters',title:'配置雷达实验参数',description:'批量更新本页教学模型参数并返回预算；只修改本页状态。',inputSchema:{type:'object',properties:props,additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('需要参数对象');const next={...p};for(const [k,v]of Object.entries(input)){const s=spec[k];if(!s||typeof v!=='number'||!Number.isFinite(v)||v<s[2]||v>s[3])throw Error('参数越界：'+k);if(k==='ifbw'&&![.5,1,3,10,15].includes(v))throw Error('LPF 仅有 0.5 / 1 / 3 / 10 / 15 MHz 五档');if(['n','mult'].includes(k)&&!Number.isInteger(v))throw Error('参数须为整数：'+k);next[k]=v;}p=next;sync();render();return{parameters:{...p},snr_db:m.snr,margin_db:m.margin,received_power_dbm:m.pr,checks:m.checks};}},{signal:life.signal})).catch(()=>{});window.addEventListener('pagehide',()=>life.abort(),{once:true});}catch{}}
render();
