import * as THREE from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {buildHardware} from './radar-hardware.js';
import {SoftwareRenderer} from './software-renderer.js';

const $=id=>document.getElementById(id);
const canvas=$('radar3d'),viewport=$('sceneViewport'),labels=$('sceneLabelsLayer'),status=$('sceneStatus');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(39,1,.1,180);
let renderer,software=false;try{const context=canvas.getContext('webgl2',{antialias:true,alpha:true});if(!context)throw Error('WebGL unavailable');renderer=new THREE.WebGLRenderer({canvas,context,antialias:true,alpha:true});renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;}catch{software=true;renderer=new SoftwareRenderer(canvas);}
const hardware=buildHardware(THREE,{expandInstances:software});scene.add(hardware.group);
renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));
scene.add(new THREE.HemisphereLight(0xc7e6ff,0x122b32,2.4));const key=new THREE.DirectionalLight(0xffeac2,2.8);key.position.set(-6,12,7);scene.add(key);const rim=new THREE.DirectionalLight(0x79cafa,1.8);rim.position.set(7,5,-8);scene.add(rim);
const grid=new THREE.GridHelper(36,36,0x2c4b5c,0x1b3444);grid.position.y=-.91;grid.material.transparent=true;grid.material.opacity=.26;scene.add(grid);
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=1.8;controls.maxDistance=65;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.02;controls.autoRotateSpeed=.5;controls.target.set(.6,0,2.9);camera.position.set(0,23.5,17.5);controls.update();
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),selectionBox=new THREE.Box3Helper(new THREE.Box3(),0x87ffd4);selectionBox.visible=false;scene.add(selectionBox);selectionBox.material.depthTest=false;selectionBox.material.transparent=true;selectionBox.material.opacity=.85;
let active='',activeChannel=null,hover='',hoverChannel=null,cameraMode='overview',showLabels=false,expanded=false,expandValue=0,expandTarget=0,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches,lastTime=0,frameClock=0,fly=null,params={fc:140,r:null},model={},dirty=true;
const connections=[['ref','pll','ref'],['ref','sample','ref'],['pll','splitter','lo35'],['splitter','vga','lo35'],['vga','vmps','lo35'],['vmps','mult','lo35'],['mult','pa','rf'],['pa','txant','rf'],['txant','target','rf'],['target','rxant','rf'],['rxant','lna','rf'],['lna','mixer','rf'],['splitter','doubler','lo35'],['doubler','mixer','lo70'],['mixer','if','if'],['if','adc','if'],['sample','adc','ref'],['adc','dsp','data'],['dsp','pll','data'],['dsp','sample','data'],['power','pll','power'],['power','pa','power'],['power','lna','power'],['power','if','power'],['power','adc','power'],['power','dsp','power'],['power','sample','power']];
const dieModules=new Set(Object.entries(hardware.modules).filter(([id,m])=>m.onDie).map(([id])=>id));
const targetStart=hardware.target.position.clone();
const palette={ref:0xecb75d,lo35:0x46b9ed,lo70:0x91d74d,rf:0xff756e,if:0x80dcce,data:0xb8a0ff,power:0xcab786},paths=[];
const baseMaterials=[];hardware.group.traverse(obj=>{if(obj.isMesh){const list=Array.isArray(obj.material)?obj.material:[obj.material];const cloned=list.map(mat=>mat.clone());obj.material=Array.isArray(obj.material)?cloned:cloned[0];for(const mat of cloned)baseMaterials.push({obj,mat,color:mat.color.clone(),emissive:mat.emissive?.clone(),glow:mat.emissiveIntensity??0});}});
function moduleId(obj){let o=obj;while(o){if(o.userData.module)return o.userData.module;o=o.parent;}return null;}
function worldAnchor(id,ch=null){const mod=hardware.modules[id],pos=(ch!=null&&mod.anchors?.[ch]?mod.anchors[ch]:mod.anchor).clone();if(id==='target')pos.add(hardware.target.position).sub(targetStart);if(dieModules.has(id))pos.y+=expandValue*1.6;return pos;}
function makeCurve(a,b,ch){const from=worldAnchor(a,ch),to=worldAnchor(b,ch),mid=from.clone().lerp(to,.5);mid.y+=a==='target'||b==='target'?.25:.65;return new THREE.CatmullRomCurve3([from,mid,to]);}
function rebuildPaths(){for(const item of paths){scene.remove(item.line);item.line.geometry.dispose();item.line.material.dispose();for(const dot of item.dots){scene.remove(dot);dot.geometry.dispose();dot.material.dispose();}}
 placeAir();paths.length=0;for(const [a,b,kind]of connections){const count=(hardware.modules[a].anchors?.length||hardware.modules[b].anchors?.length)?4:1;for(let ch=0;ch<count;ch++){const channel=count===4?ch:null,curve=makeCurve(a,b,channel),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(24)),new THREE.LineBasicMaterial({color:palette[kind],transparent:true,opacity:.48}));scene.add(line);const dots=[];for(let j=0;j<2;j++){const d=new THREE.Mesh(new THREE.SphereGeometry(.065,5,3),new THREE.MeshBasicMaterial({color:palette[kind],transparent:true,opacity:.95}));scene.add(d);dots.push(d);}paths.push({a,b,kind,ch:channel,curve,line,dots});}}applySelection();}

// Signal flow: glowing pulses travel along every board trace and cable, coloured by frequency.
const pulseGeometry=new THREE.SphereGeometry(.09,12,8),PULSE_SPEED=1.7;
function measure(f){f.lens=[0];for(let i=1;i<f.pts.length;i++)f.lens.push(f.lens[i-1]+f.pts[i].distanceTo(f.pts[i-1]));f.total=f.lens.at(-1);}
function makeFlow(f,color=palette[f.kind]){const item={...f,pts:f.points.map(p=>new THREE.Vector3(...p)),emphasis:.6};measure(item);item.mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false});const n=Math.max(1,Math.round(item.total/1.5));if(software){item.dots=Array.from({length:n},()=>{const d=new THREE.Mesh(pulseGeometry,item.mat);scene.add(d);return d;});}else{item.pulses=new THREE.InstancedMesh(pulseGeometry,item.mat,n);item.pulses.frustumCulled=false;item.count=n;scene.add(item.pulses);}item.size=1;return item;}
const pulseMatrix=new THREE.Matrix4(),pulseScale=new THREE.Vector3(),pulseQuat=new THREE.Quaternion();
function movePulses(f,t){const count=f.pulses?f.count:f.dots.length,spacing=f.total/count;pulseScale.setScalar(f.size);for(let i=0;i<count;i++){const pos=along(f,(t*PULSE_SPEED+i*spacing)%f.total);if(f.pulses)f.pulses.setMatrixAt(i,pulseMatrix.compose(pos,pulseQuat,pulseScale));else{f.dots[i].position.copy(pos);f.dots[i].scale.copy(pulseScale);}}if(f.pulses)f.pulses.instanceMatrix.needsUpdate=true;}
const flows=hardware.flows.map(f=>makeFlow(f));
// Free-space legs: each TX antenna to the target, and the echo back to each RX antenna.
function airPoints(f){const a=worldAnchor(f.from,f.from==='target'?null:f.ch),b=worldAnchor(f.to,f.to==='target'?null:f.ch);if(f.from!=='target')a.y+=.2;else b.y+=.2;return [a,b];}
for(let ch=0;ch<4;ch++)for(const [from,to,color]of [['txant','target',palette.rf],['target','rxant',0xffb3a8]]){const f=makeFlow({kind:'rf',stage:5,from,to,ch,air:true,points:airPoints({from,to,ch}).map(v=>v.toArray())},color);f.line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(f.pts),new THREE.LineBasicMaterial({color,transparent:true,opacity:.2,depthWrite:false}));scene.add(f.line);flows.push(f);}
function placeAir(){for(const f of flows)if(f.air){f.pts=airPoints(f);measure(f);f.line.geometry.setFromPoints(f.pts);}}
function along(f,s){let i=1;while(i<f.lens.length-1&&f.lens[i]<s)i++;const a=f.lens[i-1],span=f.lens[i]-a||1;return f.pts[i-1].clone().lerp(f.pts[i],(s-a)/span);}
// Radiated wavefronts toward the target and the echo returning to the RX side.
const circle=new THREE.BufferGeometry().setFromPoints(Array.from({length:40},(_,i)=>new THREE.Vector3(Math.cos(i/40*Math.PI*2),Math.sin(i/40*Math.PI*2),0)));
const waves=[];for(const kind of ['tx','echo'])for(let j=0;j<4;j++){const ring=new THREE.LineLoop(circle,new THREE.LineBasicMaterial({color:kind==='tx'?palette.rf:0xffb3a8,transparent:true,opacity:.4,depthWrite:false}));ring.userData.kind=kind;ring.userData.phase=j/4;scene.add(ring);waves.push(ring);}

// Guided tour in signal order. Numbers quoted from ISSCC 2025 Paper 10.2.
const q=x=>String(+x.toFixed(2)),fmt=(x,n=1)=>Number.isFinite(x)?x.toFixed(n):'—',beatMHz=()=>fmt(Math.abs(model.beat)/1e6,2);
const stages=[
 {mods:['ref','pll'],cam:[[-1.4,0,8.4],[-1.2,10.5,17]],title:'参考时钟 → FMCW 合成器',freq:p=>`REF → ${q(p.fc/4)} GHz`,text:p=>`外部参考为片上锁相合成器提供频率基准。合成器输出约 ${q(p.fc/4)} GHz 频段的线性调频信号（chirp），是整个 4TX-4RX 阵列唯一的频率源；论文实测扫频 34.8–40.8 GHz、周期 50 µs。`},
 {mods:['splitter'],cam:[[0,0,2.2],[0,16,13]],title:'驱动放大 + 1:8 功率分配',freq:p=>`${q(p.fc/4)} GHz × 8 路`,text:p=>`DA 先放大合成器输出，再经 1→2→4→8 分配树送出八路：右侧四路进入 TX，左侧四路作为 RX 本振。分配放在 1/4 射频频率完成，比在 ${q(p.fc)} GHz 分配损耗更低。`},
 {mods:['vga','vmps'],cam:[[3.3,0,1.2],[3.1,11.5,11]],title:'TX 幅度与相位控制',freq:p=>`${q(p.fc/4)} GHz`,text:()=>'每路 TX 先由 VGA 调节幅度，再由矢量调制相移器（VMPS）调相，论文实测 90° 范围、0.7° 分辨率。四路独立的幅相控制用于波束指向，并校准通道间误差。'},
 {mods:['mult','pa'],cam:[[7.1,0,1.2],[7.2,11.5,11]],title:'×4 倍频与功率放大',freq:p=>`${q(p.fc/4)} → ${q(p.fc)} GHz`,text:p=>`四倍频器由两级 ×2 组成，把 ${q(p.fc/4)} GHz 变为 ${q(p.fc)} GHz，并把 90° 相移范围扩展到 360°。两路合成的三级 PA 随后驱动腔体背馈天线，论文实测饱和输出 15.1 dBm。`},
 {mods:['txant','target','rxant'],cam:[[1.5,1.5,0],[2,22,24]],title:'空间辐射与目标回波',freq:p=>`${q(p.fc)} GHz · τ ≈ ${fmt(model.tau*1e9,2)} ns`,text:p=>`四路 TX 天线向目标辐射，论文实测峰值 EIRP 28.7 dBm。电磁波经目标反射后回到 RX 天线，往返延迟 τ = 2R/c；当前 R = ${fmt(p.r,1)} m，τ ≈ ${fmt(model.tau*1e9,2)} ns，回波功率随 R⁴ 衰减。`},
 {mods:['rxant','lna'],cam:[[-8.6,0,1.2],[-8.8,10.5,11]],title:'接收：低噪声放大',freq:p=>`${q(p.fc)} GHz`,text:()=>'微弱回波进入四级变压器耦合 LNA，论文实测峰值增益 20 dB、最小噪声系数 7.6 dB。LNA 的噪声性能直接决定整条接收链的灵敏度。'},
 {mods:['doubler','mixer'],cam:[[-6,0,2],[-5.8,10,11]],title:'本振倍频 + 次谐波混频',freq:p=>`LO ${q(p.fc/2)} GHz · 2×LO = ${q(p.fc)} GHz`,text:p=>`每路 RX 的 ${q(p.fc/4)} GHz 本振先经 ×2 倍频到 ${q(p.fc/2)} GHz；次谐波混频器（SHM）用 LO 的二次谐波与回波相乘去斜。回波比发射晚 τ，输出为低频拍频 f_b = S·τ − f_D，当前约 ${beatMHz()} MHz。`},
 {mods:['if'],cam:[[-3.6,0,1.2],[-3.5,9.5,10.5]],title:'模拟 IF 调理',freq:()=>`IF ≈ ${beatMHz()} MHz`,text:()=>'TIA 把混频电流转成电压，无源 HPF 抑制直流等低频分量，PGA 提供 72 dB 增益范围（6 dB 步进），6 阶 Tow-Thomas 低通截止可选 0.5 / 1 / 3 / 10 / 15 MHz，同时用于抗混叠。'},
 {mods:['if','sample','adc','dsp'],cam:[[-1,.4,9.4],[-1,11,20]],title:'采样与数字处理',freq:()=>'模拟 → 数字',text:()=>'四路差分 IF 经线缆送入外部 ADC，按采样时钟同步量化；FPGA / DSP 对每个 chirp 做距离 FFT，再跨 chirp 做多普勒 FFT，得到目标距离与速度。ADC 与 DSP 为本页教学补全，论文芯片不含。'},
];
const TOUR_DWELL=8000,tour={on:false,i:0,playing:false,start:0};
const card=$('flowCard'),startButton=$('flowStart'),steps=$('flowSteps');
stages.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`第 ${i+1} 步：${s.title}`);b.addEventListener('click',()=>setStage(i));steps.appendChild(b);});
function renderCard(){const s=stages[tour.i];$('flowIndex').textContent=`${String(tour.i+1).padStart(2,'0')} / ${String(stages.length).padStart(2,'0')}`;$('flowFreq').textContent=s.freq(params);$('flowTitle').textContent=s.title;$('flowText').textContent=s.text(params);[...steps.children].forEach((b,i)=>{b.classList.toggle('done',i<tour.i);b.setAttribute('aria-current',i===tour.i?'step':'false');});$('flowToggle').textContent=tour.playing?'暂停':'自动播放';$('flowToggle').setAttribute('aria-pressed',String(tour.playing));}
// Shift each stage view so its subject sits above-right of the narration card.
const cardShift=[-1.3,0,1.7];
function setStage(i){tour.i=(i+stages.length)%stages.length;tour.start=performance.now();const [target,position]=stages[tour.i].cam.map(v=>v.map((x,k)=>x+cardShift[k])),back=position.map((x,k)=>target[k]+(x-target[k])*1.18);flyTo(target,back);renderCard();applySelection();}
function startTour(){if(active)select('');tour.on=true;tour.playing=true;card.hidden=false;startButton.hidden=true;viewport.classList.add('touring');setStage(0);}
function endTour(){if(!tour.on)return;tour.on=false;tour.playing=false;card.hidden=true;startButton.hidden=false;viewport.classList.remove('touring');applySelection();}
startButton.addEventListener('click',startTour);$('flowClose').addEventListener('click',()=>{endTour();setCamera('overview');});
$('flowPrev').addEventListener('click',()=>setStage(tour.i-1));$('flowNext').addEventListener('click',()=>setStage(tour.i+1));
$('flowToggle').addEventListener('click',()=>{tour.playing=!tour.playing;tour.start=performance.now();renderCard();});

function selectedObject(){const g=hardware.modules[active]?.group;return activeChannel!=null?g?.children.find(x=>x.userData.channel===activeChannel)||g:g;}
function applySelection(){const relevant=new Set(active?[active]:[]);for(const [a,b]of connections)if(a===active||b===active){relevant.add(a);relevant.add(b);}const staged=tour.on&&!active?new Set(stages[tour.i].mods):null;
 for(const {obj,mat,color,emissive,glow}of baseMaterials){const id=moduleId(obj);mat.color.copy(color);if(mat.emissive){mat.emissive.copy(emissive);mat.emissiveIntensity=glow;}const sameChannel=activeChannel==null||obj.userData.channel==null||obj.userData.channel===activeChannel;
  if(active&&id&&(!relevant.has(id)||!sameChannel))mat.color.multiplyScalar(.53);if(staged&&id&&id!=='package'&&!staged.has(id))mat.color.multiplyScalar(.42);
  if(id===active&&sameChannel||id===hover&&!active||staged?.has(id)){mat.color.lerp(new THREE.Color(0xd5ffee),.17);if(mat.emissive){mat.emissive.copy(color);mat.emissiveIntensity=Math.max(glow,.22);}}}
 for(const q of paths){const strong=!!active&&(q.a===active||q.b===active)&&(activeChannel==null||q.ch==null||q.ch===activeChannel-1);q.line.visible=strong;q.line.material.opacity=strong?.85:0;for(const dot of q.dots){dot.visible=strong;dot.material.opacity=active?.95:.55;};}
 for(const f of flows){const involved=(f.from===active||f.to===active)&&(activeChannel==null||f.ch==null||f.ch===activeChannel-1);f.emphasis=tour.on&&!active?(f.stage===tour.i+1?1:.1):active?(involved?1:.07):.6;f.mat.opacity=.95*f.emphasis;f.size=f.emphasis>=1?1.45:1;f.show=f.emphasis>.05&&(!software||f.emphasis>=1);if(f.pulses)f.pulses.visible=f.show;else for(const d of f.dots)d.visible=f.show;const show=f.show;if(f.line){f.line.visible=show;f.line.material.opacity=.3*f.emphasis;}}
 selectionBox.visible=!!active;if(active)selectionBox.box.setFromObject(selectedObject());
 for(const [id,el]of labelMap)el.setAttribute('aria-pressed',String(id===active));dirty=true;
}
const labelNames={package:'系统载板',ref:'参考时钟',pll:'FMCW 合成器',vga:'VGA',vmps:'VMPS',mult:'×4 倍频器',splitter:'DA / 1:8 分配',doubler:'×2 倍频器',pa:'功率放大器',txant:'发射天线',rxant:'接收天线',lna:'低噪声放大器',mixer:'SHM 混频器',if:'模拟 IF',adc:'外部 ADC',dsp:'外部 DSP',sample:'采样时钟',power:'SPI / 电源',target:'目标'};
const txIds=new Set(['vga','vmps','mult','pa','txant']);
const labelMap=new Map();for(const [id,m]of Object.entries(hardware.modules)){const b=document.createElement('button');b.className='entity-label';b.hidden=true;b.textContent=labelNames[id];b.style.setProperty('--label-color','#'+new THREE.Color(m.color).getHexString());b.dataset.module=id;b.setAttribute('aria-label',labelNames[id]+'：选择实体');b.addEventListener('click',e=>{e.stopPropagation();endTour();select(id,id===active?activeChannel:null)});labels.appendChild(b);labelMap.set(id,b);}
function select(id,channel=null){if(id&&!hardware.modules[id])return;active=id;activeChannel=channel;applySelection();window.dispatchEvent(new CustomEvent('radar-scene-select',{detail:{id,channel}}));}
function pick(event){const r=canvas.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObject(hardware.group,true);for(const h of hits){const id=moduleId(h.object);if(id&&hardware.modules[id])return {id,channel:h.object.userData.channel||null};}return null;}
let down=null;canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};fly=null;controls.autoRotate=false;$('autoOrbit').checked=false;if(tour.playing){tour.playing=false;renderCard();}});canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5){const hit=pick(e);if(hit&&hit.id!=='package'){endTour();select(hit.id,hit.channel);}else if(!tour.on)select('');}down=null;});canvas.addEventListener('pointermove',e=>{if(down)return;const hit=pick(e);const id=hit?.id==='package'?'':hit?.id||'';hoverChannel=id?hit.channel:null;dirty=true;if(id!==hover){hover=id;canvas.style.cursor=id?'pointer':'grab';applySelection();}});canvas.addEventListener('pointerleave',()=>{hover='';applySelection()});controls.addEventListener('change',()=>dirty=true);
const presets={overview:{target:[.6,0,2.9],position:[0,23.5,17.5]},top:{target:[.7,0,2.2],position:[.7,38,3.2]},tx:{target:[6,.4,.7],position:[6,18,11]},rx:{target:[-6,.4,.7],position:[-6,18,11]},clock:{target:[.2,.4,5.1],position:[.2,14,14]},adc:{target:[-1.5,.4,10.7],position:[-1.5,10,21]},space:{target:[6,2,-.2],position:[10,19,23]}};
function flyTo(target,position){fly={fromPos:camera.position.clone(),fromTarget:controls.target.clone(),toPos:new THREE.Vector3(...position),toTarget:new THREE.Vector3(...target),start:performance.now()};controls.autoRotate=false;$('autoOrbit').checked=false;dirty=true;}
function setCamera(mode){endTour();if(mode==='overview')select('');cameraMode=mode;const preset=presets[mode];if(!preset)return;let target=preset.target,position=preset.position;flyTo(target,position);document.querySelectorAll('[data-camera]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.camera===mode)));}
function focus(id){if(!hardware.modules[id])return;const a=worldAnchor(id,activeChannel==null?null:activeChannel-1),offset=dieModules.has(id)?[0,4.7,4.5]:id==='package'?[0,30,22]:id==='target'?[-2,4,6]:[0,6,6];cameraMode='detail';document.querySelectorAll('[data-camera]').forEach(b=>b.setAttribute('aria-pressed','false'));flyTo(a.toArray(),a.clone().add(new THREE.Vector3(...offset)).toArray());}
document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>setCamera(b.dataset.camera)));$('cameraHome').addEventListener('click',()=>setCamera('overview'));$('zoomIn').addEventListener('click',()=>{camera.position.sub(controls.target).multiplyScalar(.8).add(controls.target);dirty=true});$('zoomOut').addEventListener('click',()=>{camera.position.sub(controls.target).multiplyScalar(1.25).add(controls.target);dirty=true});
$('sceneLabels').addEventListener('change',e=>{showLabels=e.target.checked;dirty=true;});$('autoOrbit').addEventListener('change',e=>{controls.autoRotate=e.target.checked;dirty=true;});$('explode').addEventListener('change',e=>{expanded=e.target.checked;expandTarget=expanded?1:0;dirty=true;});$('motion').addEventListener('click',()=>{motion=!document.body.classList.contains('paused');dirty=true;});
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(tour.on){endTour();setCamera('overview');}else if(active)select('');});
canvas.addEventListener('keydown',e=>{if(e.key==='Home'){setCamera('overview');e.preventDefault();}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){const offset=camera.position.clone().sub(controls.target),spherical=new THREE.Spherical().setFromVector3(offset);spherical.theta+=(e.key==='ArrowLeft'?.09:e.key==='ArrowRight'?-.09:0);spherical.phi=THREE.MathUtils.clamp(spherical.phi+(e.key==='ArrowUp'?-.09:e.key==='ArrowDown'?.09:0),.15,1.45);camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(spherical));dirty=true;e.preventDefault();}});
function updateLabels(){const w=viewport.clientWidth,h=viewport.clientHeight,staged=tour.on&&!active?new Set(stages[tour.i].mods):null;const candidates=[];for(const [id,el]of labelMap){const ch=id===active&&activeChannel!=null?activeChannel-1:id===hover&&hoverChannel&&id!==active?hoverChannel-1:null;el.textContent=(ch!=null?(txIds.has(id)?'TX':'RX')+(ch+1)+' · ':'')+labelNames[id];const v=worldAnchor(id,ch).add(new THREE.Vector3(0,.55,0)).project(camera);const visible=(showLabels||id===active||id===hover||staged?.has(id))&&v.z<1&&v.z>-1&&Math.abs(v.x)<.97&&Math.abs(v.y)<.9;if(!visible){el.hidden=true;continue;}const x=(v.x*.5+.5)*w,y=(-v.y*.5+.5)*h;candidates.push({id,el,x,y});}candidates.sort((a,b)=>(b.id===active||b.id===hover?1:0)-(a.id===active||a.id===hover?1:0));const occupied=[];for(const item of candidates){let y=item.y;for(let n=0;n<5;n++){if(!occupied.some(o=>Math.abs(o.x-item.x)<132&&Math.abs(o.y-y)<27))break;y-=27;}item.el.hidden=false;item.el.classList.toggle('hovered',item.id===hover&&item.id!==active);item.el.style.left=Math.max(45,Math.min(w-45,item.x))+'px';item.el.style.top=Math.max(48,y)+'px';occupied.push({x:item.x,y});}}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;if(w<10||h<10)return;renderer.setSize(w,h);camera.aspect=w/h;camera.zoom=Math.min(1,camera.aspect/1.65);camera.updateProjectionMatrix();dirty=true;}
const observer=new ResizeObserver(resize);observer.observe(viewport);resize();
const up=new THREE.Vector3(0,0,1);
function placeWave(ring,t){const tx=ring.userData.kind==='tx',from=tx?worldAnchor('txant'):worldAnchor('target'),to=tx?worldAnchor('target'):worldAnchor('rxant'),f=(t*.22+ring.userData.phase)%1,dir=to.clone().sub(from).normalize();ring.position.copy(from).lerp(to,f);ring.quaternion.setFromUnitVectors(up,dir);ring.scale.setScalar(tx?.25+f*1.1:1.2-f*.8);const focusAir=tour.on&&!active?tour.i===4:['txant','target','rxant','pa','lna'].includes(active);ring.visible=(motion||focusAir)&&(!software||focusAir)&&(!active||focusAir);ring.material.opacity=(focusAir?.7:.22)*Math.sin(Math.PI*f);}
let expansionPathTick=0;
function frame(now){requestAnimationFrame(frame);const delta=Math.min(.05,(now-lastTime)/1000||.016);lastTime=now;
 if(tour.on&&tour.playing){const progress=(now-tour.start)/TOUR_DWELL;$('flowProgress').style.transform=`scaleX(${Math.min(1,progress)})`;if(progress>=1)setStage(tour.i+1);}else if(tour.on)$('flowProgress').style.transform='scaleX(0)';
 if(document.hidden||viewport.offsetParent===null)return;
 if(fly){let t=Math.min(1,(now-fly.start)/900);t=t*t*(3-2*t);camera.position.lerpVectors(fly.fromPos,fly.toPos,t);controls.target.lerpVectors(fly.fromTarget,fly.toTarget,t);if(t>=1)fly=null;dirty=true;}
 if(Math.abs(expandValue-expandTarget)>.002){expandValue+=(expandTarget-expandValue)*Math.min(1,delta*6);for(const item of hardware.packages){const g=item.group||item;g.position.y=(item.baseY??g.userData.baseY??0)+expandValue*1.6;}expansionPathTick++;if(expansionPathTick%4===0)rebuildPaths();dirty=true;if(active)selectionBox.box.setFromObject(selectedObject());}controls.update();
 if(motion)frameClock+=delta;const t=frameClock;for(const q of paths)q.dots.forEach((dot,i)=>dot.position.copy(q.curve.getPoint((t*.23+i/2+(q.ch||0)*.08)%1)));
 for(const f of flows)if(f.show)movePulses(f,t);
 for(const ring of waves)placeWave(ring,t);
 const animating=motion&&(!software||!!active||tour.on);const refresh=dirty||animating||controls.autoRotate||fly;if(refresh&&(!software||now-(frame.lastRender||0)>55)){renderer.render(scene,camera);updateLabels();dirty=false;frame.lastRender=now;}
}
window.RadarScene={update(p,m,id,channel=null){const moved=p.r!==params.r;params={...p};model=m;if(moved){hardware.target.position.x=targetStart.x+(Math.log10(Math.max(.5,p.r))-1)*.7;rebuildPaths();}if(id&&tour.on)endTour();if(id!==active||channel!==activeChannel){active=id;activeChannel=channel;applySelection();}if(tour.on)renderCard();status.textContent=`${p.fc} GHz · 4TX / 4RX · 悬停或点击模块查看连接`;dirty=true;},focus,select,setCamera,startTour,endTour,scene,camera,hardware,renderer};
rebuildPaths();requestAnimationFrame(frame);window.dispatchEvent(new Event('radar-scene-ready'));
